sell:
    title: 物品出售
    context: 在下列物品的选项中启用你要出售的物品, 不可出售的物品不会显示在列表中. 点击提交以计算回收价格, 进行二次确认后将立即出售这些物品, 不可找回.
    confirm:
        title: 物品出售确认
        content: 你确定要出售这些物品吗? 出售这些物品将会获得以下数量的金币
        true: 确认
        false: 取消
    fail: 出售失败, 你没有可以回收的物品.
repair:
    title: 物品修复
    context: 你确定要修复你手持的这一件物品吗? 每点耐久需要 1 铜币.
    confirm: 确认
    cancel: 取消
shop:
    title: 商店
    context: 当前没有可买的东西.
attr:
    title: 属性点
    content: 在下列选项中点击要加点的属性. \n当前拥有的属性点数量 §a
    deny: 你没有足够的属性点.
general:
    no_item: 你没有可以出售的物品.
    illegal: 非法操作或您的物品栏并没有勾选的某一件物品, 请重试.
    no_money: 你没有足够的货币以完成操作.