name: RPGPocketForm
version: '${project.version}'
main: shallow.ai.rpgpocketform.RPGPocketForm
depend: [ PEFormAPI, Vault, SkillAPI, floodgate ]
authors: [ ShallowAi ]
commands:
  rpgform:
    description: 插件主要命令